(()=>{
  if(window.AIVFVideoAI)return;
  const modal=document.createElement('div'); modal.id='aivfVideoAiModal'; modal.className='hidden';
  modal.innerHTML=`<div class="vai-card"><div class="vai-head"><h3>🎬 AI VIDEO LOCAL</h3><button class="vai-secondary" id="vaiClose">✕</button></div>
  <div class="vai-status" id="vaiGpu">Đang kiểm tra GPU/model…</div>
  <div class="vai-row"><label><input type="radio" name="vaiMode" value="text" checked> Text → Video</label><label><input type="radio" name="vaiMode" value="image"> Ảnh → Video</label></div>
  <textarea id="vaiPrompt" placeholder="Ví dụ: nữ cung thủ bước về phía trước, tóc và áo choàng chuyển động tự nhiên, camera điện ảnh"></textarea>
  <div class="vai-file"><input id="vaiImage" type="file" accept="image/png,image/jpeg,image/webp"></div>
  <div class="vai-row"><label>Chất lượng <select id="vaiQuality"><option value="draft">Nháp</option><option value="balanced" selected>Cân bằng</option><option value="high">Cao</option></select></label><label>Giây <input id="vaiDuration" type="number" min="2" max="6" step="1" value="3"></label><label>FPS <input id="vaiFps" type="number" min="8" max="24" step="1" value="16"></label><label>Seed <input id="vaiSeed" type="number" value="0"></label></div>
  <div class="vai-actions"><button class="vai-primary" id="vaiCreate">✦ TẠO VIDEO</button><button class="vai-secondary" id="vaiCancel" disabled>DỪNG</button></div>
  <div class="vai-progress"><i id="vaiBar"></i></div><div class="vai-status" id="vaiStatus">Sẵn sàng.</div><video id="vaiVideo" controls class="hidden"></video></div>`;
  document.body.appendChild(modal);
  const $=id=>document.getElementById(id); let job=null,timer=null;
  async function req(url,opt={}){const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);return d}
  async function refreshStatus(){try{const s=await req('/api/ai-video/status');$('vaiGpu').textContent=s.ready?`GPU: ${s.gpu} · CUDA ${s.cuda_runtime} · T2V: ${s.t2v_model} · I2V: ${s.i2v_model}`:`AI video chưa sẵn sàng: ${s.error||'CUDA unavailable'}`;}catch(e){$('vaiGpu').textContent='Backend tao_video_ai chưa được cài/khởi động.'}}
  function open(){modal.classList.remove('hidden');refreshStatus()} function close(){modal.classList.add('hidden')}
  $('vaiClose').onclick=close; modal.addEventListener('click',e=>{if(e.target===modal)close()});
  async function poll(){if(!job)return;try{const j=await req('/api/ai-video/jobs/'+job);$('vaiBar').style.width=(j.progress||0)+'%';$('vaiStatus').textContent=`${j.stage||j.status}\n${j.detail||''}`;if(['done','error','cancelled'].includes(j.status)){clearInterval(timer);timer=null;$('vaiCreate').disabled=false;$('vaiCancel').disabled=true;if(j.status==='done'&&j.result?.url){$('vaiVideo').src=j.result.url+'?v='+Date.now();$('vaiVideo').classList.remove('hidden');$('vaiStatus').textContent+=`\nModel: ${j.result.model}\nEncoder: ${j.result.encoder}\nVRAM peak: ${j.result.vram_peak_bytes?Math.round(j.result.vram_peak_bytes/1048576)+' MB':'n/a'}`;}job=null;}}catch(e){$('vaiStatus').textContent='Lỗi poll: '+e.message}}
  $('vaiCreate').onclick=async()=>{try{const mode=document.querySelector('input[name=vaiMode]:checked').value,prompt=$('vaiPrompt').value.trim(),quality=$('vaiQuality').value,duration=+$('vaiDuration').value,fps=+$('vaiFps').value,seed=+$('vaiSeed').value;let d;if(mode==='text'){if(prompt.length<3)throw new Error('Nhập mô tả video.');d=await req('/api/ai-video/jobs/text',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,quality,duration,fps,seed})});}else{const file=$('vaiImage').files[0];if(!file)throw new Error('Chọn ảnh đầu vào.');const f=new FormData();f.append('file',file);f.append('prompt',prompt);f.append('quality',quality);f.append('duration',duration);f.append('fps',fps);f.append('seed',seed);d=await req('/api/ai-video/jobs/image',{method:'POST',body:f});}job=d.job_id;$('vaiCreate').disabled=true;$('vaiCancel').disabled=false;$('vaiVideo').classList.add('hidden');$('vaiBar').style.width='1%';timer=setInterval(poll,900);poll();}catch(e){$('vaiStatus').textContent='Lỗi: '+e.message}};
  $('vaiCancel').onclick=async()=>{if(job){await req(`/api/ai-video/jobs/${job}/cancel`,{method:'POST'}).catch(()=>{});$('vaiStatus').textContent='Đang yêu cầu dừng…'}};
  function installButton(){if($('aivfVideoAiBtn'))return;const btn=document.createElement('button');btn.id='aivfVideoAiBtn';btn.className='btn accent';btn.textContent='🎬 AI VIDEO';btn.onclick=open;const top=document.querySelector('header .actions,.topbar,.header-actions,.toolbar')||document.querySelector('header')||document.body;top.appendChild(btn)}
  installButton();window.AIVFVideoAI={open,close,refreshStatus};
})();
