(() => {
  const S=window.Studio,$=S.$;let segments=[],sourceLanguage='en';
  function render(){const box=$('captionList');box.innerHTML='';segments.forEach((s,i)=>{const d=document.createElement('div');d.className='caption-row';d.innerHTML=`<span>${S.fmt(s.start)}–${S.fmt(s.end)}</span><textarea data-i="${i}">${S.esc(s.text)}</textarea>`;d.querySelector('textarea').oninput=e=>segments[i].text=e.target.value;box.appendChild(d)});if(!segments.length)box.innerHTML='<div class="hint">Chưa có phụ đề.</div>';$('captionApply').disabled=!segments.length}
  $('captionTranscribe').onclick=async()=>{if(!S.hasVideo())return S.setStatus('Tải video lên trước.',true);S.setBusy(true,'Whisper local đang nghe và tạo phụ đề…');try{const d=await S.jsonRequest(`/api/editor/${S.state.sessionId}/captions/transcribe`,{method:'POST'});segments=d.segments||[];sourceLanguage=d.language||'en';render();S.setStatus(`Đã tạo ${segments.length} câu bằng ${d.engine||'Whisper local'} · ngôn ngữ ${sourceLanguage}.`)}catch(e){S.setStatus('Lỗi phụ đề local: '+e.message,true)}finally{S.setBusy(false)}};
  $('captionTranslate').onclick=async()=>{if(!segments.length)return S.setStatus('Tạo phụ đề trước.',true);S.setBusy(true,'Model dịch local đang xử lý…');try{const d=await S.jsonRequest('/api/captions/translate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({segments,source_language:sourceLanguage,target_language:$('captionLanguage').value})});segments=d.segments||[];sourceLanguage=languageCode($('captionLanguage').value);render();S.setStatus('Dịch local xong. Lần đầu mỗi cặp ngôn ngữ có thể cần tải model miễn phí.')}catch(e){S.setStatus('Lỗi dịch local: '+e.message,true)}finally{S.setBusy(false)}};
  function languageCode(v){return ({Vietnamese:'vi',English:'en',Japanese:'ja',Korean:'ko',Chinese:'zh',Thai:'th',Spanish:'es',French:'fr'})[v]||v}
  $('captionApply').onclick=()=>{if(!segments.length)return;const p=window.TextTemplates?.getPreset($('captionPreset').value)||window.TextTemplates?.all()?.[0];segments.slice(0,150).forEach(s=>{const l=S.newLayer({type:'text',name:'CC '+s.text,text:s.text,widthRatio:.65,color:p?.color||'#fff',outlineColor:p?.outline_color||'#000',outlineWidth:p?.outline_width??4,background:p?.background||'#000',backgroundOpacity:p?.background_opacity??.2,fontFamily:p?.font_family||'segoe',fontSizeRatio:p?.font_size_ratio||.05,shadowColor:p?.shadow_color||'#000',shadowOpacity:p?.shadow_opacity||0,shadowBlur:p?.shadow_blur||0});l.start=Math.max(0,+s.start||0);l.end=Math.min(S.state.duration,+s.end||l.start+2);l.x=.5;l.y=.84;S.createLayerElement(l)});S.renderTimeline();S.setStatus(`Đã đưa ${Math.min(segments.length,150)} câu phụ đề lên video.`)};
  render();
})();
