(() => {
  const S=window.Studio,$=S.$;let selectedAudio=null;
  function selected(name,audioId){selectedAudio={name,audio_id:audioId};$('musicSelected').classList.remove('hidden');$('musicSelected').innerHTML=`<strong>${S.esc(name)}</strong><small>Đã sẵn sàng để ghép vào video</small>`;$('musicApply').disabled=!S.hasVideo()}
  $('musicVolume').oninput=e=>$('musicVolumeLabel').textContent=e.target.value+'%';
  $('musicSearch').onclick=async()=>{const wish=$('musicWish').value.trim();S.setBusy(true,'Đang tìm trong kho nhạc local…');try{const d=await S.jsonRequest('/api/music/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({wish,limit:18})});renderResults(d.items||[]);S.setStatus('Gợi ý local theo: '+(d.query||'tất cả'))}catch(e){S.setStatus('Lỗi tìm nhạc local: '+e.message,true)}finally{S.setBusy(false)}};
  function renderResults(items){const box=$('musicResults');box.innerHTML='';items.forEach(t=>{const d=document.createElement('div');d.className='music-card';d.innerHTML=`<div class="music-meta"><strong>${S.esc(t.name)}</strong><small>Kho local · ${(t.tags||[]).map(S.esc).join(', ')}</small><audio controls preload="none" src="${S.esc(t.preview||'')}"></audio></div><button class="btn accent">Dùng bài này</button>`;d.querySelector('button').onclick=()=>importLocal(t);box.appendChild(d)});if(!items.length)box.innerHTML='<div class="hint">Chưa có bài phù hợp. Tải file nhạc của bạn lên; nó sẽ tự lưu vào kho local.</div>'}
  async function importLocal(track){if(!S.hasVideo())return S.setStatus('Tải video lên trước.',true);S.setBusy(true,'Đang nhập nhạc local…');try{const d=await S.jsonRequest(`/api/editor/${S.state.sessionId}/music/import-library`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({track_id:track.id})});selected(track.name,d.audio_id);S.setStatus('Đã nhập nhạc từ kho local.')}catch(e){S.setStatus('Lỗi nhập nhạc: '+e.message,true)}finally{S.setBusy(false)}}
  $('musicLocalFile').onchange=async e=>{const f=e.target.files[0];if(!f||!S.hasVideo())return;S.setBusy(true,'Đang tải nhạc và lưu vào kho local…');const form=new FormData();form.append('file',f);try{const d=await S.jsonRequest(`/api/editor/${S.state.sessionId}/music/upload`,{method:'POST',body:form});selected(f.name,d.audio_id);$('musicLocalName').textContent=f.name;S.setStatus('Nhạc đã sẵn sàng và được lưu vào kho local.')}catch(err){S.setStatus('Lỗi tải nhạc: '+err.message,true)}finally{S.setBusy(false);e.target.value=''}};
  $('musicApply').onclick=async()=>{if(!selectedAudio||!S.hasVideo())return;S.setBusy(true,'Đang ghép nhạc vào video…');try{const payload={audio_id:selectedAudio.audio_id,clip_duration:+$('musicDuration').value,insert_at:+$('musicInsertAt').value||0,volume:+$('musicVolume').value/100,keep_original:$('musicKeepOriginal').checked,smart_excerpt:$('musicSmart').checked};const d=await S.jsonRequest(`/api/editor/${S.state.sessionId}/music/apply`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});S.applyInfo(d);S.setStatus(`Đã thêm nhạc. Đoạn nổi bật bắt đầu khoảng ${d.music_excerpt_start??0}s trong bài.`)}catch(e){S.setStatus('Lỗi ghép nhạc: '+e.message,true)}finally{S.setBusy(false)}};
  $('musicSearch').click();
})();
