(() => {
  if (window.AIVFMapHD?.version === '3.0-main-stage') return;
  const $ = (s, r = document) => r.querySelector(s);
  const $$ = (s, r = document) => [...r.querySelectorAll(s)];
  const state = { active:false, quality:'standard', jobId:null, pollTimer:null, manifest:null, chunksManifest:null, sourceUrl:null, zoom:1, panX:0, panY:0, dragging:false, lastX:0, lastY:0, header:null, stageSnapshot:null };

  const panelMarkup = () => `
    <div class="panel-title">BẢN ĐỒ HD</div>
    <div class="notice">Khóa bố cục tổng, chia tile HD và ghép liền mạch. Ảnh mẫu và map hiển thị trong khung lớn.</div>
    <div class="ai-ref-row"><div class="dropzone map-hd-upload" id="mapHdUploadBox"><button type="button" id="mapHdChooseFile">＋ CHỌN ẢNH MẪU</button><strong id="mapHdFileName">Chưa chọn ảnh</strong><span>PNG/JPG/WebP · hiển thị ngay trong khung lớn</span><input id="mapHdImageFile" type="file" accept="image/png,image/jpeg,image/webp" hidden></div><button type="button" class="btn" id="mapHdImageClear" hidden>✖ Bỏ ảnh</button></div>
    <div class="field section-gap"><label>Mô tả map</label><textarea id="mapHdPrompt" placeholder="Giữ bố cục ảnh mẫu; khóa vị trí vùng chính, đường, sông, bờ biển; bỏ chữ/nhãn/UI..."></textarea></div>
    <div class="field"><label>Chất lượng</label><div class="map-hd-quality"><button type="button" data-q="lite">NHẸ</button><button type="button" class="active" data-q="standard">TRUNG BÌNH</button><button type="button" data-q="final">ĐẸP</button></div></div>
    <div class="field"><label>Số tile</label><select id="mapHdTiles"><option value="">Tự tính theo chất lượng</option><option>4</option><option>6</option><option>8</option><option>10</option><option>12</option><option>16</option><option>20</option></select></div>
    <button type="button" class="map-hd-create" id="mapHdCreate">✦ TẠO MAP HD</button>
    <div class="map-hd-progress section-gap"><div><b id="mapHdProgressStage">Sẵn sàng</b><strong id="mapHdPct">0%</strong></div><div class="map-hd-track"><i id="mapHdBar"></i></div><small id="mapHdDetail">Trung bình là mặc định.</small></div>
    <div class="map-hd-actions" id="mapHdActions"></div>`;

  function isActive() { const p=$('#panel-bandohd'); return Boolean(p && !p.classList.contains('hidden') && !document.body.classList.contains('home-mode')); }
  function rememberHeader() { if(!state.header) state.header={title:$('.preview-head h2')?.textContent||'',meta:$('#videoMeta')?.textContent||'',hint:$('.preview-head-actions > span')?.textContent||''}; }
  function setHeader(meta='Chưa có bản đồ') { rememberHeader(); if($('.preview-head h2'))$('.preview-head h2').textContent='BẢN ĐỒ HD'; if($('#videoMeta'))$('#videoMeta').textContent=meta; if($('.preview-head-actions > span'))$('.preview-head-actions > span').textContent='Kéo để xem · cuộn để zoom'; }
  function restoreHeader() { if(!state.header)return; if($('.preview-head h2'))$('.preview-head h2').textContent=state.header.title; if($('#videoMeta'))$('#videoMeta').textContent=state.header.meta; if($('.preview-head-actions > span'))$('.preview-head-actions > span').textContent=state.header.hint; state.header=null; }
  function setMapStageActive(active) {
    if(active && !state.active){state.stageSnapshot=['#empty','#videoBox','#ai3dSourcePreview','#ai3dStageViewer','#realtimePreview'].map(selector=>({selector,hidden:$(selector)?.classList.contains('hidden')}));}
    state.active=active;document.body.classList.toggle('map-hd-active',active);$('#mapHdStageViewer')?.classList.toggle('hidden',!active);
    if(active){$('#empty')?.classList.add('hidden');$('#videoBox')?.classList.add('hidden');$('#ai3dSourcePreview')?.classList.add('hidden');$('#ai3dStageViewer')?.classList.add('hidden');$('#realtimePreview')?.classList.add('hidden');setHeader(state.manifest?'Map HD hoàn tất':'Chưa có bản đồ');}
    else{for(const item of state.stageSnapshot||[]){const el=$(item.selector);if(el)el.classList.toggle('hidden',item.hidden);}state.stageSnapshot=null;restoreHeader();}
  }
  function activate(){setMapStageActive(true);if(state.manifest)showMap();else if(state.sourceUrl)showSource(state.sourceUrl);else showEmpty('Chọn ảnh mẫu hoặc nhập mô tả để tạo bản đồ.');if(state.jobId&&!state.pollTimer&&!state.manifest)pollJob();}
  function deactivate(){clearTimeout(state.pollTimer);state.pollTimer=null;state.dragging=false;setMapStageActive(false);}
  function showEmpty(text){$('#mapHdEmpty').textContent=text;$('#mapHdEmpty').classList.remove('hidden');$('#mapHdViewport').classList.add('hidden');$('#mapHdLoading').classList.add('hidden');}
  function showSource(url){setMapStageActive(true);$('#mapHdEmpty').classList.add('hidden');$('#mapHdLoading').classList.add('hidden');$('#mapHdViewport').classList.remove('hidden');const c=$('#mapHdCanvas');c.className='map-hd-canvas map-hd-source-canvas';c.innerHTML='<img class="map-hd-source-image" alt="Ảnh mẫu bản đồ">';$('.map-hd-source-image',c).src=url;c.style.transform='';setHeader('Ảnh mẫu bản đồ');}
  function showLoading(stage='Đang phân tích bố cục...',pct=0,detail=''){setMapStageActive(true);$('#mapHdEmpty').classList.add('hidden');$('#mapHdViewport').classList.add('hidden');$('#mapHdLoading').classList.remove('hidden');$('#mapHdLoadingStage').textContent=stage;$('#mapHdLoadingPct').textContent=`${Math.round(pct)}%`;$('#mapHdLoadingBar').style.width=`${Math.max(0,Math.min(100,pct))}%`;$('#mapHdLoadingDetail').textContent=detail;setHeader(`${Math.round(pct)}% · ${stage}`);}
  function updateProgress(stage,pct,detail){const p=Number(pct)||0;$('#mapHdProgressStage').textContent=stage||'Đang xử lý';$('#mapHdPct').textContent=`${Math.round(p)}%`;$('#mapHdBar').style.width=`${Math.max(0,Math.min(100,p))}%`;$('#mapHdDetail').textContent=detail||'';if(state.active)showLoading(stage||'Đang xử lý',p,detail||'');}
  function setBusy(busy){const b=$('#mapHdCreate');if(b){b.disabled=busy;b.textContent=busy?'ĐANG TẠO...':'✦ TẠO MAP HD';}}
  function previewUrl(d){return d.preview_url||d.preview_image_url||d.current_tile_url||d.tile_preview_url||d.current_tile_output||'';}

  async function createMap(){
    if(state.pollTimer)return;const file=$('#mapHdImageFile')?.files?.[0],prompt=$('#mapHdPrompt')?.value.trim()||'';
    if(!file&&!prompt)return window.Studio?.setStatus?.('Cần ảnh mẫu hoặc mô tả map.',true);
    setBusy(true);showLoading('Đang phân tích bố cục...',0,'Khởi tạo job Bản đồ HD');updateProgress('Đang phân tích bố cục...',0,'Khởi tạo job Bản đồ HD');
    const form=new FormData();form.append('prompt',prompt);form.append('quality',state.quality);if($('#mapHdTiles')?.value)form.append('tile_count',$('#mapHdTiles').value);const route=file?'/api/ban-do-3d/tao-tu-anh':'/api/ban-do-3d/tao-tu-mo-ta';if(file)form.append('file',file);
    try{const r=await fetch(route,{method:'POST',body:form}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||`API ${r.status}`);if(!d.job_id)throw new Error('Backend không trả job_id');state.jobId=d.job_id;window.AIVFJobTerminal?.start({scope:'map_hd',jobId:d.job_id,title:'ĐANG TẠO MAP HD'});pollJob();}catch(e){window.AIVFJobTerminal?.fail('Không tạo được job Map HD',e.message);failJob(e.message);}
  }
  async function pollJob(){
    clearTimeout(state.pollTimer);
    try{const r=await fetch(`/api/ban-do-3d/job/${state.jobId}`,{cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||`Job API ${r.status}`);const stage=d.stage||d.status||'Đang xử lý',pct=Number(d.progress)||0,tile=d.current_tile||d.tile_index||d.current_tile_index,total=d.tile_count||d.total_tiles,detail=d.detail||(tile?`Đang tạo tile ${tile}${total?`/${total}`:''}`:'');updateProgress(stage,pct,detail);if(previewUrl(d)){showSource(previewUrl(d));$('#mapHdState').textContent=`${Math.round(pct)}% · ${stage}${detail?` · ${detail}`:''}`;}if(d.status==='completed'){await loadMap(d);setBusy(false);state.pollTimer=null;return;}if(['failed','cancelled'].includes(d.status)){failJob(d.error||(d.status==='cancelled'?'Job đã bị hủy':'Job tạo map thất bại'));return;}if(state.active)state.pollTimer=setTimeout(pollJob,900);}catch(e){failJob(e.message);}
  }
  function failJob(message){clearTimeout(state.pollTimer);state.pollTimer=null;state.jobId=null;setBusy(false);updateProgress('Không thể tạo bản đồ',0,message);$('#mapHdLoadingStage').textContent='Không thể tạo bản đồ';$('#mapHdLoadingDetail').textContent=message;window.Studio?.setStatus?.(`Không thể tạo bản đồ: ${message}`,true);}
  async function loadMap(job){const manifestUrl=job.manifest_url||`/api/ban-do-3d/job/${state.jobId}/manifest`,r=await fetch(manifestUrl,{cache:'no-store'});if(!r.ok)throw new Error(`Không đọc được manifest (${r.status})`);state.manifest=await r.json();showMap();const width=job.width||state.manifest.width||'?',height=job.height||state.manifest.height||'?',passed=job.validation?.pass===true;$('#mapHdProgressStage').textContent=passed?'Map nền PASS':'Map nền chưa PASS';$('#mapHdPct').textContent='100%';$('#mapHdBar').style.width='100%';$('#mapHdDetail').textContent=`${state.manifest.tiles?.length||job.tile_count||0} tile HD · ${width}×${height}px · border ${Math.round((job.validation?.border_score||0)*100)}% · nét ${Math.round((job.validation?.sharpness_score||0)*100)}%`;$('#mapHdActions').innerHTML=`<a href="/api/ban-do-3d/job/${state.jobId}/full" target="_blank">MAP FULL</a><a href="${manifestUrl}" target="_blank">MANIFEST</a>${passed?'<button type="button" id="mapHdSplitChunks">TÁCH KHU VỰC</button><button type="button" id="mapHdPlaceAssets">ĐẶT ĐỒ VẬT</button>':''}`;if(passed){$('#mapHdSplitChunks').onclick=splitChunks;$('#mapHdPlaceAssets').onclick=()=>window.dispatchEvent(new CustomEvent('aivf-map-place-assets',{detail:{jobId:state.jobId}}));}setHeader(`Map nền HD · ${width}×${height}px · ${passed?'PASS':'CHƯA PASS'}`);}
  async function splitChunks(){const button=$('#mapHdSplitChunks');if(button){button.disabled=true;button.textContent='ĐANG TÁCH KHU VỰC...';}showLoading('Đang tách map thành khu vực',96,'Chỉ crop pixel HD từ map tổng đã PASS');try{const response=await fetch(`/api/ban-do-3d/job/${state.jobId}/chunks`,{method:'POST'}),result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.detail||`API ${response.status}`);const manifestResponse=await fetch(result.chunks_manifest_url,{cache:'no-store'});if(!manifestResponse.ok)throw new Error('Không đọc được chunk manifest');state.chunksManifest=await manifestResponse.json();showChunks();$('#mapHdProgressStage').textContent='Tách khu vực PASS';$('#mapHdDetail').textContent=`${result.chunk_count} chunk · overlap ${result.overlap}px · rebuild ${Math.round((result.chunk_validation?.rebuild_similarity||0)*10000)/100}%`;$('#mapHdActions').innerHTML=`<button type="button" id="mapHdShowMaster">MAP TỔNG</button><a href="${result.chunks_manifest_url}" target="_blank">CHUNK MANIFEST</a><a href="${result.rebuild_url}" target="_blank">REBUILD</a>`;$('#mapHdShowMaster').onclick=showMap;}catch(error){showLoading('Không thể tách khu vực',0,error.message);if(button){button.disabled=false;button.textContent='TÁCH MAP THÀNH KHU VỰC';}}}
  function showChunks(){const manifest=state.chunksManifest;if(!manifest)return;setMapStageActive(true);$('#mapHdEmpty').classList.add('hidden');$('#mapHdLoading').classList.add('hidden');$('#mapHdViewport').classList.remove('hidden');const canvas=$('#mapHdCanvas');canvas.className='map-hd-canvas map-hd-chunk-canvas';canvas.innerHTML='';canvas.style.gridTemplateColumns=`repeat(${manifest.cols},minmax(150px,1fr))`;for(const chunk of manifest.chunks){const cell=document.createElement('button');cell.type='button';cell.className='map-hd-chunk';cell.innerHTML=`<img src="/api/ban-do-3d/job/${state.jobId}/chunks/${chunk.chunk_id}" alt="${chunk.chunk_id}"><span><b>${chunk.chunk_id}</b><small>X ${chunk.world_x} · Z ${chunk.world_z} · ${chunk.biome}</small></span>`;cell.onclick=()=>{showSource(`/api/ban-do-3d/job/${state.jobId}/chunks/${chunk.chunk_id}`);$('#mapHdState').textContent=`${chunk.chunk_id} · X ${chunk.world_x} · Z ${chunk.world_z} · ${chunk.width}×${chunk.height} · ${chunk.biome}`;};canvas.appendChild(cell);}canvas.style.transform='';setHeader(`${manifest.chunk_count} khu vực · overlap ${manifest.overlap}px`);}
  function showMap(){if(!state.manifest)return;setMapStageActive(true);$('#mapHdEmpty').classList.add('hidden');$('#mapHdLoading').classList.add('hidden');$('#mapHdViewport').classList.remove('hidden');const c=$('#mapHdCanvas'),m=state.manifest,cols=Number(m.cols)||1,size=Math.min(768,Math.max(256,Math.round((Number(m.tile_size)||1024)/2)));c.className='map-hd-canvas map-hd-tile-canvas';c.innerHTML='';c.style.gridTemplateColumns=`repeat(${cols},${size}px)`;for(const t of m.tiles||[]){const img=document.createElement('img');img.alt=t.tile_id||'Map tile';img.title=`${t.tile_id} · X ${t.world_x} · Z ${t.world_z} · ${t.biome}`;img.src=t.url||`/api/ban-do-3d/job/${state.jobId}/tile/${t.tile_id}?v=${Date.now()}`;img.style.width=`${size}px`;img.style.height=`${size}px`;img.onclick=()=>{$('#mapHdState').textContent=img.title;showSource(img.src);};c.appendChild(img);}state.zoom=1;state.panX=0;state.panY=0;requestAnimationFrame(fitMap);}
  function applyTransform(){const c=$('#mapHdCanvas');if(c?.classList.contains('map-hd-tile-canvas'))c.style.transform=`translate(${state.panX}px,${state.panY}px) scale(${state.zoom})`;$('#mapHdZoomText').textContent=`${Math.round(state.zoom*100)}%`;}
  function zoom(kind){if(kind==='in')state.zoom=Math.min(6,state.zoom*1.25);else if(kind==='out')state.zoom=Math.max(.08,state.zoom/1.25);else{state.zoom=1;state.panX=0;state.panY=0;}applyTransform();}
  function fitMap(){const v=$('#mapHdViewport'),c=$('#mapHdCanvas');if(!v||!c||!state.manifest)return;const w=c.scrollWidth||1,h=c.scrollHeight||1;state.zoom=Math.min((v.clientWidth-32)/w,(v.clientHeight-32)/h,1);state.panX=(v.clientWidth-w*state.zoom)/2;state.panY=(v.clientHeight-h*state.zoom)/2;applyTransform();}

  function bindStage(){const v=$('#mapHdStageViewer');if(!v)return;v.insertAdjacentHTML('beforeend','<div class="map-hd-loading hidden" id="mapHdLoading"><strong>BẢN ĐỒ HD</strong><b id="mapHdLoadingStage">Đang phân tích bố cục...</b><div class="map-hd-loading-track"><i id="mapHdLoadingBar"></i></div><em id="mapHdLoadingPct">0%</em><small id="mapHdLoadingDetail"></small></div>');const toolbar=$('.map-hd-toolbar',v);if(toolbar&&!$('#mapHdGridButton'))toolbar.insertAdjacentHTML('beforeend','<button type="button" id="mapHdGridButton">LƯỚI TILE</button><button type="button" id="mapHdBackToMap">MAP TỔNG</button>');$('#mapHdGridButton').onclick=()=>$('#mapHdCanvas')?.classList.toggle('grid-on');$('#mapHdBackToMap').onclick=showMap;$('#mapHdZoomOut').onclick=()=>zoom('out');$('#mapHdZoomReset').onclick=()=>zoom('reset');$('#mapHdZoomIn').onclick=()=>zoom('in');$('#mapHdViewport').addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY<0?'in':'out');},{passive:false});$('#mapHdViewport').addEventListener('mousedown',e=>{if(!state.manifest)return;state.dragging=true;state.lastX=e.clientX;state.lastY=e.clientY;});window.addEventListener('mousemove',e=>{if(!state.dragging||!state.active)return;state.panX+=e.clientX-state.lastX;state.panY+=e.clientY-state.lastY;state.lastX=e.clientX;state.lastY=e.clientY;applyTransform();});window.addEventListener('mouseup',()=>{state.dragging=false;});}
  function clearMapImage(){$('#mapHdImageFile').value='';if(state.sourceUrl){URL.revokeObjectURL(state.sourceUrl);state.sourceUrl=null;}$('#mapHdFileName').textContent='Chưa chọn ảnh';$('#mapHdImageClear').hidden=true;showEmpty('Chọn ảnh mẫu hoặc nhập mô tả để tạo bản đồ.');}
  function bindPanel(){const panel=$('#panel-bandohd');if(!panel)return;panel.innerHTML=panelMarkup();$$('.map-hd-quality button',panel).forEach(b=>b.onclick=()=>{$$('.map-hd-quality button',panel).forEach(x=>x.classList.remove('active'));b.classList.add('active');state.quality=b.dataset.q;});$('#mapHdChooseFile').onclick=()=>{$('#mapHdImageFile').value='';$('#mapHdImageFile').click();};$('#mapHdImageFile').onchange=e=>{const f=e.target.files?.[0];if(!f)return;if(state.sourceUrl)URL.revokeObjectURL(state.sourceUrl);state.sourceUrl=URL.createObjectURL(f);$('#mapHdFileName').textContent=f.name;$('#mapHdImageClear').hidden=false;showSource(state.sourceUrl);$('#mapHdProgressStage').textContent='Ảnh mẫu đã chọn';$('#mapHdDetail').textContent='Ảnh đã hiện trong khung lớn.';};$('#mapHdImageClear').onclick=clearMapImage;$('#mapHdCreate').onclick=createMap;}
  function mount(){bindStage();bindPanel();$('#homeBtn')?.addEventListener('click',deactivate);if(isActive())activate();window.addEventListener('beforeunload',()=>{clearTimeout(state.pollTimer);if(state.sourceUrl)URL.revokeObjectURL(state.sourceUrl);});}
  window.AIVFMapHD={version:'3.0-main-stage',open:activate,close:deactivate,setMapStageActive,fitMap};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();
