from __future__ import annotations
from .core_types import ToolSpec
class ToolRegistry:
    def __init__(self): self._tools={x.name:x for x in self._default_specs()}
    def _default_specs(self):
        def s(name,target,description,inputs,outputs,side_effects,requirements=None,limitations=None,success=None,evidence=None,failure=None):
            return ToolSpec(name,target,description,inputs,outputs,side_effects,requirements or [],limitations or [],success or ['tool reports success'],evidence or ['tool_status'],failure or ['tool reports failure'])
        return [
            s('code_analyze','maintenance','Đọc/phân tích code, không sửa.',{'scope':'path/code'},{'analysis':'text'},[],['resolved target'],['Không ghi file.'],['analysis produced'],['analysis_text']),
            s('code_edit','maintenance','Sửa code đúng phạm vi, backup và test.',{'path':'file','changes':'requested changes'},{'files':'updated'},['writes source files'],['resolved target','backup','required arguments'],[],['requested change confirmed','tests pass'],['target_exists','write_confirmed','syntax_check','expected_change']),
            s('file_read','maintenance','Đọc file.',{'path':'file'},{'content':'text'},[],['resolved path'],[],['content read'],['read_confirmed']),
            s('file_write','maintenance','Ghi file.',{'path':'file','content':'data'},{'file':'updated'},['writes file'],['resolved path','backup','required arguments'],[],['write confirmed'],['target_exists','write_confirmed']),
            s('zip_extract','maintenance','Giải nén ZIP.',{'zip':'file','destination':'path'},{'files':'extracted'},['writes files'],['required arguments'],[],['files extracted'],['destination_exists','files_created']),
            s('zip_create','maintenance','Tạo ZIP.',{'paths':'files'},{'zip':'file'},['creates archive'],['required arguments'],[],['archive exists'],['artifact_exists','write_confirmed']),
            s('image_generate_edit','aiimage','Tạo/chỉnh ẢNH 2D PHẲNG bằng AI - NHẸ, NHANH, KHÔNG dựng mesh/khối 3D. Đây là tool ĐÚNG khi owner chỉ nói "ảnh"/"ảnh AI"/"tạo ảnh"/"hình" mà KHÔNG hề nhắc "3D"/"mô hình"/"model"/"mesh"/"game". Ví dụ "tạo một ảnh AI nhân vật nữ" → tool này, KHÔNG PHẢI character_3d_generate.',{'prompt':'str','reference_image':'optional'},{'image':'file'},['creates output image'],['required arguments'],['Không tạo rig/animation 3D.'],['image artifact valid'],['artifact_exists','artifact_type_image','write_confirmed']),
            s('character_2d_generate','character2d','Tạo nhân vật 2D dạng ảnh (vẫn là ẢNH PHẲNG, không dựng mesh 3D). Chỉ chọn khi owner nói rõ "nhân vật 2D" hoặc đang trong luồng làm nhân vật 2D có sẵn - không phải lựa chọn mặc định cho "tạo ảnh nhân vật" chung chung (đó là image_generate_edit).',{'prompt':'str'},{'image':'file'},['creates output image'],['required arguments'],[],['image artifact valid'],['artifact_exists','artifact_type_image','write_confirmed']),
            s('character_3d_generate','ai3d','Tạo nhân vật 3D (dựng mesh 3D thật - NẶNG, chạy Hunyuan3D/diffusers, tốn nhiều phút + VRAM/RAM). CHỈ dùng khi owner nói RÕ RÀNG "3D"/"mô hình"/"model"/"mesh"/"game"/"khối" ở lượt này.',{'prompt':'str','color':'bool - true nếu owner muốn tự động tô màu/texture sau khi dựng khối; false/thiếu = chỉ dựng khối xám, chưa có màu'},{'mesh':'asset'},['creates 3D asset'],['required arguments'],['Bước này chỉ dựng mesh tĩnh + tô màu (nếu color=true) - KHÔNG tự có rig/animation, không nháy mắt. Muốn nhân vật đi/chạy/tấn công/mấp máy miệng thì dùng thêm tool game_ready_convert SAU KHI đã có model này - đó là bước riêng, không tự động nối tiếp.', 'QUAN TRỌNG: nếu owner chỉ nói "ảnh"/"ảnh AI"/"tạo ảnh" mà KHÔNG nhắc "3D" ở lượt NÀY, ĐỪNG tự chọn tool này chỉ vì active_task/current_target trước đó đang là ai3d - đó là ngữ cảnh CŨ của lượt trước, lượt owner đang nói mới là nguồn sự thật; owner đổi ý sang muốn ảnh phẳng thì phải chọn image_generate_edit hoặc character_2d_generate.', 'QUAN TRỌNG: nếu có ảnh tham chiếu đính kèm (files không rỗng), pipeline dựng 3D TRỰC TIẾP TỪ HÌNH DẠNG THẬT trong ảnh đó - mô tả chữ chỉ chỉnh màu/phong cách, KHÔNG thể đổi vũ khí/trang phục/dáng khác hẳn những gì đã thấy trong ảnh (vd ảnh có cung thì kết quả vẫn cầm cung dù chữ ghi "cầm đao"). Nếu owner mô tả 1 vũ khí/trang phục KHÁC hẳn ảnh đính kèm đang có, đó là dấu hiệu ảnh cũ không còn phù hợp - nên để files rỗng (dùng mô tả chữ thuần, tự vẽ concept mới) thay vì vẫn đính kèm ảnh cũ, và set needs_user nêu rõ lý do.'],['3D artifact valid'],['artifact_exists','artifact_type_3d','write_confirmed']),
            s('object_3d_generate','dovat3d','Tạo đồ vật 3D.',{'prompt':'str','texture':'bool - true nếu owner muốn tự động tô texture sau khi dựng khối; false/thiếu = chỉ dựng khối, chưa có texture'},{'mesh':'asset'},['creates 3D asset'],['required arguments'],[],['3D artifact valid'],['artifact_exists','artifact_type_3d','write_confirmed']),
            s('game_ready_convert','gameready','Gắn xương (rig) + animation THẬT (idle/chạy/tấn công theo đúng vũ khí) vào model 3D nhân vật ĐÃ có sẵn (vừa tạo gần nhất trong phiên) - không tạo model mới, chỉ nâng cấp model có sẵn.',{'target_faces':'int optional - số poly mục tiêu, mặc định 45000 nếu owner không nói rõ','weapon_type':"str optional - LOẠI VŨ KHÍ NHÂN VẬT ĐANG CẦM: 'sword'/'kiếm'/'đao' (chém nhiều góc), 'staff'/'gậy'/'trượng' (xoay + đập từ trên xuống, 2 tay), 'spear'/'thương'/'giáo' (đâm thẳng về trước, 2 tay), 'bow'/'cung' (giương cung bắn). QUAN TRỌNG: nếu owner không nhắc lại vũ khí ở câu này, XEM LẠI các lượt hội thoại TRƯỚC ĐÓ (lúc tạo nhân vật) xem owner đã nói cầm gì - dùng đúng vũ khí đó, đừng mặc định 'bow' nếu owner rõ ràng đã nói cầm thứ khác."},{'mesh':'asset'},['creates rigged animated 3D asset'],[],['Chỉ áp dụng cho model 3D vừa tạo gần nhất trong phiên, không tự chọn model khác. Animation tấn công chỉ là tư thế thân/tay (không có prop cung/dây/mũi tên hay lưỡi kiếm thật). Có thêm 1 clip "talk" (mấp máy hàm) THỬ NGHIỆM - vị trí xương hàm là suy đoán hình học, không đảm bảo lúc nào cũng trông tự nhiên, cần owner tự xem model để xác nhận. KHÔNG nháy mắt, không tóc động (chưa có xương/blend-shape cho mắt).'],['rig+skin+3 animation clip (idle/run/attack) valid qua kiểm tra thật, không tự nhận nếu chưa verify'],['artifact_exists','artifact_type_3d','write_confirmed']),
            s('map_hd_generate','bandohd','Tạo bản đồ HD.',{'prompt':'str'},{'map':'artifact'},['creates output'],['required arguments'],[],['map artifact valid'],['artifact_exists','write_confirmed']),
        ]
    def get(self,name): return self._tools.get(str(name or ''))
    def by_target(self,target):
        for t in self._tools.values():
            if t.target==target:return t
        return None
    def public_list(self): return [x.public_dict() for x in self._tools.values()]
